-- Add the new public gallery categories while retaining legacy values for existing rows.
ALTER TYPE "GalleryCategory" ADD VALUE IF NOT EXISTS 'DAILY_LIFE_GROWTH' BEFORE 'EDUCATION';
ALTER TYPE "GalleryCategory" ADD VALUE IF NOT EXISTS 'COMMUNITY_FELLOWSHIP' BEFORE 'EDUCATION';
ALTER TYPE "GalleryCategory" ADD VALUE IF NOT EXISTS 'LEARNING_CREATIVITY' BEFORE 'EDUCATION';
ALTER TYPE "GalleryCategory" ADD VALUE IF NOT EXISTS 'EVENTS_MILESTONES' BEFORE 'EDUCATION';
ALTER TYPE "GalleryCategory" ADD VALUE IF NOT EXISTS 'OTHERS' BEFORE 'EDUCATION';
